print("\u2602") # UMBRELLA
print("\u2603") # SNOWMAN
print("\u2620") # SKULL AND CROSSBONES
print("\u2622") # RADIOACTIVE SIGN
print("\u3020") # POSTAL MARK FACE
print("\u2368") # APL FUNCTIONAL SYMBOL TILDE DIAERESIS
print("\ufdfa") # ARABIC LIGATURE SALLALLAHOU ALAYHE WASALLAM
print("\U0001f46f") # WOMAN WITH BUNNY EARS
print("\u0e5b") # THAI CHARACTER KHOMUT
print("\u2619") # REVERSED ROTATED FLORAL HEART BULLET
print("\u203d") # INTERROBANG
print("\u0f12") # TIBETAN MARK RGYA GRAM SHAD
print("\u0f17") # TIBETAN ASTROLOGICAL SIGN SGRA GCAN -CHAR RTAGS
print("\U0001f4b8") # MONEY WITH WINGS
